### ISSUE TITLE
Bug related to padding in the Register component

### ISSUE THREAD

**Issue by roerohan** [roerohan/8086.js#19]
# Bug related to padding in the Register component

In the `Register` component, the values of the registers are displayed in `hex` and are padded to 4 digits using the `padStart` function. This works fine when the register is being displayed on the UI.

However, one of the features of `8086.js` is that you can edit the value in a register and execute instructions with the updated value. Now, because of the `padStart` in the UI, updating a register becomes somewhat weird, since you can not delete a number (the `padStart` function will always ensure that there are 4 characters). So, you would have to add a 5th number to be able to delete a number that is already present.

This can possibly be resolved by using the `padStart` function when the user focuses out of the `register` box. This might be related to #18 , since the padding would vary for `hex`, `binary`, `octal`, and `decimal` numbers.

https://github.com/roerohan/8086.js/blob/017505bca69da4b7e803a2cd3e5353f9a14c5660/src/components/Register/index.jsx#L49-L62

**Comment by capellini** [comment]
@roerohan My proposed solution can be found in #22.  Please let me know what you think, at your convenience.

**Comment by roerohan** [comment]
Hi @capellini ,

Thanks a lot for contributing :four_leaf_clover: 

One issue I see in this is as follows:

When you are viewing the number, it is going to be in `hex`. (E.G. 000a)
When you focus, it will become integer all of a sudden. (E.G. 000a becomes 10)
Once you blur again, the value that you write is considered to be a `hex` value. (E.G. if you write 10, it becomes 0x10 instead of 10 in decimal)

This could be somewhat confusing for users. Here's something I just came up with:
- Instead of storing a decimal number as obtained from `registers[name]` in the `regValue` variable, you could convert it to `hex` before-hand.
> In fact, you could create a function which of the form `convert(reg, base)` which converts `registers[name]` to the specified base (16 for hex, 10 for decimal, etc.) which would make it easier to implement #18 later. You would now set the state as useState(convert(registers[name], 16)).

- In your `handleBlur()` function, you could prepend the required number of `0`s and store it in the state with `setRegValue`.
- Now you wouldn't need a `handleFocus()` since your register is padded _only_ upon focus.

I haven't tested this, but I think this might work.
Feel free to come up with better alternatives :smiley: 

Also, could you please move the PR to the `dev` branch instead of `master`?

**Comment by capellini** [comment]
@roerohan You're most welcome! 

I just used the built-in `parseInt`, rather than creating my own convert function.  Does 3926361abcd291b32cf7c44d13bcc627dd127f33 work?

Apologies for commit to `master` instead of `dev` -- I'll move it.

**Comment by roerohan** [comment]
https://github.com/roerohan/8086.js/commit/3926361abcd291b32cf7c44d13bcc627dd127f33#diff-b49c6c99c74b7c5fcf61090635d175b6R35

@capellini 
Looks good to me :+1: 

You could still make the other change, where you pad _only_ on blur (if you want), then you could get rid of the `handleFocus` function, and the `editing` state variable altogether.

**Comment by capellini** [comment]
> You could still make the other change, where you pad _only_ on blur (if you want), then you could get rid of the `handleFocus` function, and the `editing` state variable altogether.

Ok.  I'll take a look.

**Comment by capellini** [comment]
@roerohan Do we always want the register values in base 10 and only convert to hexadecimal when displaying in the Register component?

**Comment by roerohan** [comment]
@capellini Yes, the CPU assumes that the registers are in base 10 when on performing the operations. In the `register` component, we ultimately aim to be able to display the values of the registers in base 2, 8, 10, and 16. In the future, a dropdown would be displayed to the user for selecting the base, and somehow passed as a prop or in the `redux` state to the component.

**Comment by capellini** [comment]
@roerohan I think the latest commit does the trick:

- Store as decimal values, convert to hex and pad when displaying
- Add a 'base' prop, with a default value of 16
- Ensure that values do not exceed `0xffff` before storing them
- Filter out/ignore invalid user input

**Comment by capellini** [comment]
I have also written some tests to ensure proper behavior of the Register component and the redux store and to prevent regressions.  Would you like me to add that to #23, or save it for another PR after that one is merged?

**Comment by roerohan** [comment]
> I have also written some tests to ensure proper behavior of the Register component and the redux store and to prevent regressions. Would you like me to add that to #23, or save it for another PR after that one is merged?

@capellini you can make another PR to `dev` for this :+1: 

This issue is fixed, thanks a lot :tada:
