### ISSUE TITLE
suggestion: use `yarn` to handle dependencies.

### ISSUE THREAD

**Issue by DarkCode01** [roerohan/8086.js#24]
I get those errors and alerts that are shown in the image below when I try to install the libraries with `npm install` I tried clearing the cache but it still did not install the libraries.

Everything worked fine when installed using `yarn`, my recommendation is to use `yarn` to manage project dependencies.

<img width="1256" alt="Screen Shot 2020-09-24 at 10 24 31 PM" src="https://user-images.githubusercontent.com/23442814/94219510-008d0900-feb5-11ea-8f0e-5ea8ea28f97b.png">

**Comment by roerohan** [comment]
@DarkCode01 
I'm guessing #25 fixes this, since you added a `yarn.lock` file?

**Comment by DarkCode01** [comment]
@roerohan  yes but we also need to update the REAME.md documentation :D

**Comment by roerohan** [comment]
I requested a small change, could you get that done?
