### ISSUE TITLE
Logo for 8086.js

### ISSUE THREAD

**Issue by roerohan** [roerohan/8086.js#30]
# Logo for 8086.js

This one is about design. `8086.js` needs a logo and a favicon (could be the same).
- The logo will be added to the [README.md](https://github.com/roerohan/8086.js)
- The favicon will be placed in the `public` directory.

Please place both (or one if they're the same) the files in the `public` directory and PR to the `dev` branch :pleading_face:

**Comment by Sanjana-R** [comment]
I’d like to take this up.

**Comment by roerohan** [comment]
Great @Sanjana-R 
I'll assign this to you :100:

**Comment by roerohan** [comment]
Thanks for the logo @Sanjana-R
