### ISSUE TITLE
Theme switcher for the entire page

### ISSUE THREAD

**Issue by roerohan** [roerohan/8086.js#41]
# Theme switcher for the entire page

Thanks to @DarkCode01 , we have a theme switcher implemented for the Editor (#40 ). However, it would be amazing to have a theme switcher for the entire page!
 
> [This](https://c7f.github.io/C7F-Frontend/) is probably a good example of what we're looking for.

The goal is that when you switch from say the `dracula` theme to the `github` theme, the entire page should be colored like the github theme and not just the `Editor` component.

**Comment by namsnath** [comment]
Hey,
I can work on extending the theming to the entire app

**Comment by roerohan** [comment]
Sounds good! 
This is what it looks like currently, I think you know what to do :partying_face: 
I'll assign this to you

![image](https://user-images.githubusercontent.com/42958812/94797063-3d995400-03fd-11eb-913a-bf65d81d2f74.png)

**Comment by namsnath** [comment]
Thanks!

**Comment by roerohan** [comment]
Thanks @namsnath for fixing this :D
